### ISSUE TITLE
How can i  use this as a ingress?

### ISSUE THREAD

**Issue by TheYkk** [nwtgck/docker-nginx-http3#1]
I have k3s kubernetes cluster and how can i use http 3 as a ingress?

**Comment by nwtgck** [comment]
Hi @TheYkk,

Unfortunately, I'm not familiar with Kubernetes. I just found:
- [Development - NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/development/)
- [ingress-nginx/images/nginx at master · kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/master/images/nginx)

Although I did try those and not read yet, I hope that information useful and someone who knows Kubernetes leave a comment.

**Comment by TheYkk** [comment]
i used with load balancer service type and i didn't use ingress.
